"""Translate a small permission policy into per-agent allow/deny files."""

from __future__ import annotations

import json
import re
import shlex
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from agentrecall.layout import Layout

MANAGED_HEADER = "# Generated by agentrecall. Edit permissions.yaml, not this file.\n"
CODEX_TOML_BEGIN = "# BEGIN agentrecall-managed"
CODEX_TOML_END = "# END agentrecall-managed"
DEFAULT_HISTORY_WRITE = "~/.agents/history"

INIT_TEMPLATE = f"""\
# Canonical permission policy for agentrecall.
# This is not a dump of Claude/Cursor/Codex approval history.
# Only prefixes and hosts listed here are translated.
#
# Unmapped on purpose: MCP tool ids, one-off approved commands,
# bypass/YOLO modes, and full OS sandbox profiles.
# external_write becomes extra writable roots where a tool documents them.

allow_shell:
  - git status
  - git diff
  - git log
  - ls
  - agentrecall
deny_shell:
  - git push --force
  - git push -f
allow_fetch:
  - github.com
workspace_write: true
external_write:
  - {DEFAULT_HISTORY_WRITE}
"""


@dataclass(frozen=True, slots=True)
class PermissionPolicy:
    allow_shell: tuple[str, ...] = ()
    deny_shell: tuple[str, ...] = ()
    allow_fetch: tuple[str, ...] = ()
    workspace_write: bool = True
    external_write: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class NativeRules:
    claude_allow: tuple[str, ...] = ()
    claude_deny: tuple[str, ...] = ()
    claude_additional_dirs: tuple[str, ...] = ()
    claude_sandbox_allow_write: tuple[str, ...] = ()
    cursor_allow: tuple[str, ...] = ()
    cursor_deny: tuple[str, ...] = ()
    opencode_bash: dict[str, str] = field(default_factory=dict)
    opencode_fetch: dict[str, str] = field(default_factory=dict)
    opencode_edit: str | None = None
    opencode_external: dict[str, str] = field(default_factory=dict)
    codex_rules: str = ""
    codex_writable_roots: tuple[str, ...] = ()
    skipped: tuple[str, ...] = ()


def git_toplevel(cwd: Path) -> Path | None:
    current = cwd.resolve()
    for candidate in [current, *current.parents]:
        if (candidate / ".git").exists():
            return candidate
    return None


def project_permissions_file(root: Path) -> Path:
    return root / ".agents" / "permissions.yaml"


def project_managed_file(root: Path) -> Path:
    return root / ".agents" / "permissions.managed.json"


def _string_list(value: object, key: str) -> tuple[str, ...]:
    if value is None:
        return ()
    if not isinstance(value, list):
        raise ValueError(f"{key} must be a list of strings")
    items: list[str] = []
    for item in value:
        if not isinstance(item, str) or not item.strip():
            raise ValueError(f"{key} entries must be non-empty strings")
        items.append(item.strip())
    return tuple(items)


def parse_policy(data: object) -> PermissionPolicy:
    if data is None:
        return PermissionPolicy()
    if not isinstance(data, dict):
        raise ValueError("permissions.yaml must be a mapping")
    workspace = data.get("workspace_write", True)
    if not isinstance(workspace, bool):
        raise ValueError("workspace_write must be a boolean")
    return PermissionPolicy(
        allow_shell=_string_list(data.get("allow_shell"), "allow_shell"),
        deny_shell=_string_list(data.get("deny_shell"), "deny_shell"),
        allow_fetch=_string_list(data.get("allow_fetch"), "allow_fetch"),
        workspace_write=workspace,
        external_write=_string_list(data.get("external_write"), "external_write"),
    )


def load_policy_file(path: Path) -> PermissionPolicy | None:
    if not path.is_file():
        return None
    try:
        loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ValueError(f"{path} is not valid YAML: {exc}") from exc
    return parse_policy(loaded)


def _fetch_host(raw: str) -> str:
    host = raw.strip()
    for prefix in ("https://", "http://"):
        if host.startswith(prefix):
            host = host[len(prefix) :]
    return host.split("/")[0]


def _shell_tokens(command: str) -> list[str] | None:
    try:
        tokens = shlex.split(command)
    except ValueError:
        return None
    if not tokens:
        return None
    if any(token == "*" and index == 0 for index, token in enumerate(tokens)):
        return None
    return tokens


def _claude_bash(command: str) -> str:
    if command.endswith("*") or ":*" in command:
        return f"Bash({command})"
    return f"Bash({command}:*)"


def _cursor_shell(command: str) -> str:
    return f"Shell({command})"


def _starlark_list(tokens: list[str]) -> str:
    inner = ", ".join(json.dumps(token) for token in tokens)
    return f"[{inner}]"


def expand_external_path(raw: str) -> str:
    expanded = Path(raw).expanduser()
    if not expanded.is_absolute():
        expanded = Path.home() / expanded
    return str(expanded)


def compile_native(policy: PermissionPolicy) -> NativeRules:
    skipped: list[str] = []
    claude_allow: list[str] = []
    claude_deny: list[str] = []
    cursor_allow: list[str] = []
    cursor_deny: list[str] = []
    opencode_bash: dict[str, str] = {"*": "ask"}
    opencode_fetch: dict[str, str] = {}
    opencode_external: dict[str, str] = {}
    codex_blocks: list[str] = [MANAGED_HEADER]

    for command in policy.allow_shell:
        tokens = _shell_tokens(command)
        if tokens is None:
            skipped.append(f"allow_shell {command!r} (could not parse)")
            continue
        claude_allow.append(_claude_bash(command))
        cursor_allow.append(_cursor_shell(command))
        opencode_bash[f"{command} *"] = "allow"
        if command.endswith("*"):
            opencode_bash[command] = "allow"
        pattern = [token for token in tokens if token != "*"]
        if not pattern:
            skipped.append(f"allow_shell {command!r} (too broad for Codex)")
        else:
            codex_blocks.append(
                "prefix_rule(\n"
                f"    pattern = {_starlark_list(pattern)},\n"
                '    decision = "allow",\n'
                '    justification = "agentrecall allow_shell",\n'
                ")\n"
            )

    for command in policy.deny_shell:
        tokens = _shell_tokens(command)
        if tokens is None:
            skipped.append(f"deny_shell {command!r} (could not parse)")
            continue
        claude_deny.append(_claude_bash(command))
        cursor_deny.append(_cursor_shell(command))
        opencode_bash[f"{command} *"] = "deny"
        pattern = [token for token in tokens if token != "*"]
        if pattern:
            codex_blocks.append(
                "prefix_rule(\n"
                f"    pattern = {_starlark_list(pattern)},\n"
                '    decision = "forbidden",\n'
                '    justification = "agentrecall deny_shell",\n'
                ")\n"
            )

    for host_raw in policy.allow_fetch:
        host = _fetch_host(host_raw)
        if not host:
            skipped.append(f"allow_fetch {host_raw!r} (empty host)")
            continue
        claude_allow.append(f"WebFetch(domain:{host})")
        cursor_allow.append(f"WebFetch({host})")
        opencode_fetch[f"*{host}*"] = "allow"

    opencode_edit = "allow" if policy.workspace_write else None
    if policy.workspace_write:
        claude_allow.extend(["Edit", "Write"])

    claude_additional_dirs: list[str] = []
    claude_sandbox_allow_write: list[str] = []
    codex_writable_roots: list[str] = []
    for path in policy.external_write:
        expanded = expand_external_path(path)
        opencode_external[expanded] = "allow"
        claude_additional_dirs.append(expanded)
        claude_sandbox_allow_write.append(expanded)
        codex_writable_roots.append(expanded)
    if policy.external_write:
        skipped.append(
            "external_write (Cursor has no portable extra-root mapping; "
            "Shell(agentrecall) is allowlisted instead)"
        )

    return NativeRules(
        claude_allow=tuple(dict.fromkeys(claude_allow)),
        claude_deny=tuple(dict.fromkeys(claude_deny)),
        claude_additional_dirs=tuple(dict.fromkeys(claude_additional_dirs)),
        claude_sandbox_allow_write=tuple(dict.fromkeys(claude_sandbox_allow_write)),
        cursor_allow=tuple(dict.fromkeys(cursor_allow)),
        cursor_deny=tuple(dict.fromkeys(cursor_deny)),
        opencode_bash=opencode_bash,
        opencode_fetch=opencode_fetch,
        opencode_edit=opencode_edit,
        opencode_external=opencode_external,
        codex_rules="".join(codex_blocks),
        codex_writable_roots=tuple(dict.fromkeys(codex_writable_roots)),
        skipped=tuple(skipped),
    )


def _read_json(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path} is not valid JSON: {exc}") from exc
    if not isinstance(loaded, dict):
        raise ValueError(f"{path} is not a JSON object")
    return loaded


def _write_json(path: Path, data: dict[str, Any], *, dry_run: bool) -> str:
    text = json.dumps(data, indent=2) + "\n"
    if dry_run:
        return f"would write {path}"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return f"wrote    {path}"


def _load_managed(path: Path) -> dict[str, list[str]]:
    if not path.is_file():
        return {}
    loaded = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(loaded, dict):
        return {}
    out: dict[str, list[str]] = {}
    for key, value in loaded.items():
        if isinstance(value, list) and all(isinstance(item, str) for item in value):
            out[key] = value
    return out


def _splice(existing: list[str], old_managed: list[str], new_managed: tuple[str, ...]) -> list[str]:
    old = set(old_managed)
    kept = [item for item in existing if item not in old]
    for item in new_managed:
        if item not in kept:
            kept.append(item)
    return kept


def _permissions_bucket(data: dict[str, Any]) -> dict[str, Any]:
    bucket = data.get("permissions")
    if not isinstance(bucket, dict):
        bucket = {}
        data["permissions"] = bucket
    return bucket


def apply_claude_settings(
    path: Path,
    rules: NativeRules,
    managed: dict[str, list[str]],
    *,
    dry_run: bool,
) -> str:
    data = _read_json(path)
    bucket = _permissions_bucket(data)
    allow = [item for item in bucket.get("allow", []) if isinstance(item, str)]
    deny = [item for item in bucket.get("deny", []) if isinstance(item, str)]
    bucket["allow"] = _splice(allow, managed.get("claude_allow", []), rules.claude_allow)
    bucket["deny"] = _splice(deny, managed.get("claude_deny", []), rules.claude_deny)
    additional = [item for item in bucket.get("additionalDirectories", []) if isinstance(item, str)]
    bucket["additionalDirectories"] = _splice(
        additional,
        managed.get("claude_additional_dirs", []),
        rules.claude_additional_dirs,
    )
    filesystem = _sandbox_filesystem(data)
    allow_write = [item for item in filesystem.get("allowWrite", []) if isinstance(item, str)]
    filesystem["allowWrite"] = _splice(
        allow_write,
        managed.get("claude_sandbox_allow_write", []),
        rules.claude_sandbox_allow_write,
    )
    managed["claude_allow"] = list(rules.claude_allow)
    managed["claude_deny"] = list(rules.claude_deny)
    managed["claude_additional_dirs"] = list(rules.claude_additional_dirs)
    managed["claude_sandbox_allow_write"] = list(rules.claude_sandbox_allow_write)
    return _write_json(path, data, dry_run=dry_run)


def _sandbox_filesystem(data: dict[str, Any]) -> dict[str, Any]:
    sandbox = data.get("sandbox")
    if not isinstance(sandbox, dict):
        sandbox = {}
        data["sandbox"] = sandbox
    filesystem = sandbox.get("filesystem")
    if not isinstance(filesystem, dict):
        filesystem = {}
        sandbox["filesystem"] = filesystem
    return filesystem


def apply_cursor_cli(
    path: Path,
    rules: NativeRules,
    managed: dict[str, list[str]],
    *,
    dry_run: bool,
) -> str:
    if not path.is_file() and dry_run:
        return f"would skip {path}  (Cursor CLI config does not exist yet)"
    if not path.is_file():
        data: dict[str, Any] = {"version": 1}
    else:
        data = _read_json(path)
    bucket = _permissions_bucket(data)
    allow = [item for item in bucket.get("allow", []) if isinstance(item, str)]
    deny = [item for item in bucket.get("deny", []) if isinstance(item, str)]
    bucket["allow"] = _splice(allow, managed.get("cursor_allow", []), rules.cursor_allow)
    bucket["deny"] = _splice(deny, managed.get("cursor_deny", []), rules.cursor_deny)
    managed["cursor_allow"] = list(rules.cursor_allow)
    managed["cursor_deny"] = list(rules.cursor_deny)
    return _write_json(path, data, dry_run=dry_run)


def apply_opencode(
    path: Path,
    rules: NativeRules,
    managed: dict[str, list[str]],
    *,
    dry_run: bool,
) -> str:
    data = _read_json(path)
    permission: dict[str, Any] = {}
    if isinstance(data.get("permission"), dict):
        permission = dict(data["permission"])

    bash_existing = permission.get("bash")
    bash: dict[str, str] = {}
    if isinstance(bash_existing, dict):
        old = set(managed.get("opencode_bash", []))
        bash = {key: value for key, value in bash_existing.items() if key not in old}
    bash.update(rules.opencode_bash)
    permission["bash"] = bash
    managed["opencode_bash"] = list(rules.opencode_bash.keys())

    if rules.opencode_fetch:
        fetch_existing = permission.get("webfetch")
        fetch: dict[str, str] = {}
        if isinstance(fetch_existing, dict):
            old = set(managed.get("opencode_fetch", []))
            fetch = {key: value for key, value in fetch_existing.items() if key not in old}
        fetch.update(rules.opencode_fetch)
        permission["webfetch"] = fetch
        managed["opencode_fetch"] = list(rules.opencode_fetch.keys())

    if rules.opencode_edit is not None:
        permission["edit"] = rules.opencode_edit
    if rules.opencode_external:
        permission["external_directory"] = dict(rules.opencode_external)
    data["permission"] = permission
    return _write_json(path, data, dry_run=dry_run)


def apply_codex_rules(path: Path, rules: NativeRules, *, dry_run: bool) -> str:
    if dry_run:
        return f"would write {path}"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rules.codex_rules, encoding="utf-8")
    return f"wrote    {path}"


def _toml_string_array(values: list[str]) -> str:
    inner = ", ".join(json.dumps(item) for item in values)
    return f"[{inner}]"


def _strip_managed_toml(text: str) -> str:
    pattern = re.compile(
        rf"\n*{re.escape(CODEX_TOML_BEGIN)}.*?{re.escape(CODEX_TOML_END)}\s*",
        re.DOTALL,
    )
    stripped = pattern.sub("\n", text)
    return stripped.rstrip() + ("\n" if stripped.strip() else "")


def apply_codex_writable_roots(
    path: Path,
    rules: NativeRules,
    managed: dict[str, list[str]],
    *,
    dry_run: bool,
) -> str:
    roots = list(rules.codex_writable_roots)
    old_managed = managed.get("codex_writable_roots", [])
    existing_text = path.read_text(encoding="utf-8") if path.is_file() else ""
    stripped = _strip_managed_toml(existing_text)
    parsed: dict[str, Any] = {}
    if stripped.strip():
        parsed = tomllib.loads(stripped)

    table = parsed.get("sandbox_workspace_write")
    if isinstance(table, dict):
        current = table.get("writable_roots", [])
        current_list = [str(item) for item in current] if isinstance(current, list) else []
        merged = _splice(current_list, old_managed, tuple(roots))
        array = _toml_string_array(merged)
        if re.search(r"writable_roots\s*=", stripped):
            new_text = re.sub(
                r"writable_roots\s*=\s*\[[^\]]*\]",
                f"writable_roots = {array}",
                stripped,
                count=1,
            )
        else:
            new_text = re.sub(
                r"(\[sandbox_workspace_write\])",
                rf"\1\nwritable_roots = {array}",
                stripped,
                count=1,
            )
    elif roots:
        block = (
            f"{CODEX_TOML_BEGIN}\n"
            "[sandbox_workspace_write]\n"
            f"writable_roots = {_toml_string_array(roots)}\n"
            f"{CODEX_TOML_END}\n"
        )
        new_text = (stripped.rstrip() + "\n\n" + block) if stripped.strip() else block
    else:
        new_text = stripped

    managed["codex_writable_roots"] = roots
    if dry_run:
        return f"would write {path}"
    if not roots and not path.is_file():
        return f"skip     {path}  no extra writable roots"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(new_text if new_text.endswith("\n") else new_text + "\n", encoding="utf-8")
    return f"wrote    {path}"


def preview_lines(policy: PermissionPolicy, rules: NativeRules, origin: str) -> list[str]:
    lines = [
        f"policy: {origin}",
        f"  allow_shell: {len(policy.allow_shell)}",
        f"  deny_shell:  {len(policy.deny_shell)}",
        f"  allow_fetch: {len(policy.allow_fetch)}",
        f"  workspace_write: {policy.workspace_write}",
        f"  external_write: {len(policy.external_write)}",
        "",
        "claude allow:",
        *_preview_items(rules.claude_allow),
        "claude extra dirs:",
        *_preview_items(rules.claude_additional_dirs),
        "claude deny:",
        *_preview_items(rules.claude_deny),
        "cursor allow:",
        *_preview_items(rules.cursor_allow),
        "codex rules: prefix_rule allow/forbidden in agentrecall.rules",
        "codex writable_roots:",
        *_preview_items(rules.codex_writable_roots),
        "opencode: permission.bash / webfetch / edit / external_directory",
    ]
    if rules.skipped:
        lines.extend(["", "not translated:"])
        lines.extend(f"  {item}" for item in rules.skipped)
    return lines


def _preview_items(items: tuple[str, ...]) -> list[str]:
    if not items:
        return ["  (none)"]
    return [f"  {item}" for item in items]


def init_policy(path: Path, *, dry_run: bool) -> str:
    if path.exists():
        return f"skip     {path}  already exists"
    if dry_run:
        return f"would write {path}"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(INIT_TEMPLATE, encoding="utf-8")
    return f"wrote    {path}"


def sync_permissions(
    layout: Layout,
    *,
    cwd: Path | None,
    dry_run: bool,
) -> tuple[list[str], int]:
    user_policy = load_policy_file(layout.permissions_file)
    root = git_toplevel(cwd) if cwd is not None else None
    if cwd is not None and root is None:
        root = cwd.resolve()
    project_path = project_permissions_file(root) if root is not None else None
    project_policy = load_policy_file(project_path) if project_path is not None else None

    if user_policy is None and project_policy is None:
        return [
            "no permissions.yaml found; run `agentrecall permissions init` "
            "or `agentrecall permissions init --cwd .`"
        ], 1

    lines: list[str] = []
    if dry_run:
        lines.append("dry-run (pass --apply to write)")

    if user_policy is not None:
        rules = compile_native(user_policy)
        lines.extend(
            preview_lines(user_policy, rules, str(layout.permissions_file))
        )
        managed_user = _load_managed(layout.permissions_managed_file)
        lines.append(
            apply_claude_settings(
                layout.claude_home / "settings.json",
                rules,
                managed_user,
                dry_run=dry_run,
            )
        )
        lines.append(
            apply_cursor_cli(
                layout.cursor_home / "cli-config.json",
                rules,
                managed_user,
                dry_run=dry_run,
            )
        )
        lines.append(
            apply_codex_rules(
                layout.codex_home / "rules" / "agentrecall.rules",
                rules,
                dry_run=dry_run,
            )
        )
        lines.append(
            apply_codex_writable_roots(
                layout.codex_home / "config.toml",
                rules,
                managed_user,
                dry_run=dry_run,
            )
        )
        lines.append(
            apply_opencode(
                layout.opencode_home / "opencode.json",
                rules,
                managed_user,
                dry_run=dry_run,
            )
        )
        if not dry_run:
            _write_json(layout.permissions_managed_file, managed_user, dry_run=False)

    if project_policy is not None and root is not None and project_path is not None:
        if user_policy is not None:
            lines.append("")
        rules = compile_native(project_policy)
        lines.extend(preview_lines(project_policy, rules, str(project_path)))
        managed_project = _load_managed(project_managed_file(root))
        lines.append(
            apply_claude_settings(
                root / ".claude" / "settings.json",
                rules,
                managed_project,
                dry_run=dry_run,
            )
        )
        lines.append(
            apply_codex_rules(
                root / ".codex" / "rules" / "agentrecall.rules",
                rules,
                dry_run=dry_run,
            )
        )
        lines.append(
            apply_codex_writable_roots(
                root / ".codex" / "config.toml",
                rules,
                managed_project,
                dry_run=dry_run,
            )
        )
        opencode_project = root / "opencode.json"
        if not opencode_project.is_file():
            opencode_project = root / ".opencode" / "opencode.json"
        lines.append(
            apply_opencode(opencode_project, rules, managed_project, dry_run=dry_run)
        )
        lines.append(
            "skip     Cursor CLI  (cli-config.json is user-global; project rules are not isolated)"
        )
        if not dry_run:
            _write_json(project_managed_file(root), managed_project, dry_run=False)

    return lines, 0
